CREATE TABLE IF NOT EXISTS account (
    USER_ID CHAR(10) PRIMARY KEY,
    PASS VARCHAR(10) NOT NULL,
    MAIL VARCHAR(100) NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    AGE INT NOT NULL
);

INSERT INTO account (USER_ID, PASS, MAIL, NAME, AGE) VALUES('minato', '1234', 'minato@sukkiri.com', '田中 太郎', 23);